In [1]:
import pandas as pd

#Series

In [ ]:
a = [1,20,7,5]
b = pd.Series(a)
b

0     1
1    20
2     7
3     5
dtype: int64

In [ ]:
#giving column name
b.name = "numbers"
b

0     1
1    20
2     7
3     5
Name: numbers, dtype: int64

In [ ]:
#label
a = pd.Series([1,7,5],index=["X","Y","Z"])
a.name = "index"
a

X    1
Y    7
Z    5
Name: index, dtype: int64

In [ ]:
data = { "day1": 420, "day2": 380, "day3": 390 }
a = pd.Series(data)
print(a)

day1    420
day2    380
day3    390
dtype: int64

#DataFrame

In [ ]:
data = {
    "calories": [420,380,390],
    "duration": [50,40,45]
}

var = pd.DataFrame(data)
print(var)

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
data = {
    "calories": [420,380,390],
    "duration": [50,40,45]
}

df = pd.DataFrame(data,index=["day1","day2","day3"])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

#Reading csv file

In [ ]:
d = pd.read_csv("/content/drive/MyDrive/Sinro Robotics/data.csv")
print(d.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

#Reading json file

In [ ]:
j = pd.read_json("/content/drive/MyDrive/Sinro Robotics/data.json")
print(j)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

#Exploring Dataset

In [ ]:
# df.head()      # first 5 rows
# df.tail()      # last 5 rows
# df.columns     # column names
# df.shape       # (rows, columns)
# df.info()      # data types
# df.describe()  # statistics

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Sinro Robotics/data.csv")
print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
# df.head() - Shows first 5 rows

df.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [ ]:
df.head(22)

    Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    106       128     345.3
13        60    104       132     379.3
14        60     98       123     275.0
15        60     98       120     215.2
16        60    100       120     300.0
17        45     90       112       NaN
18        60    103       123     323.0
19        45     97       125     243.0
20        60    108       131     364.2
21        45    100       119     282.0

In [ ]:
# df.tail() - Shows last 5 rows

df.tail()

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
df.tail(2)

     Duration  Pulse  Maxpulse  Calories
167        75    120       150     320.4
168        75    125       150     330.4

In [ ]:
# df.columns - Shows column names

df.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [ ]:
# df.index → row labels

df.index

RangeIndex(start=0, stop=169, step=1)

In [ ]:
# df.shape - Shows (rows, columns)

df.shape

(169, 4)

In [ ]:
# df.info() - Gives complete summary

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [ ]:
# df.describe() - Gives statistical summary

df.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

# practice

In [ ]:
# import pandas as pd

# data = {
#     "Name": ["A", "B", "C", "D", "E"],
#     "Age": [20, 25, 30, 22, 28],
#     "Marks": [85, 90, 78, 88, 92]
# }

# df = pd.DataFrame(data)

# df.head(3)
# df.tail(2)
# df.columns
# df.shape
# df.info()
# df.describe()

#Selecting Columns

In [ ]:

data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [20, 25, 30, 22, 28]
}

df = pd.DataFrame(data)
print(df)

  Name  Age
0    A   20
1    B   25
2    C   30
3    D   22
4    E   28

In [ ]:
#Selecting one column - Output is a Series

df["Name"] #Single bracket → Series

0    A
1    B
2    C
3    D
4    E
Name: Name, dtype: object

In [ ]:
# Select multiple columns - Output is a DataFrame

df[["Name", "Age"]] #Double bracket → DataFrame

  Name  Age
0    A   20
1    B   25
2    C   30
3    D   22
4    E   28

#Selecting Rows

In [ ]:
# Using index

df.iloc[0]

Name     A
Age     20
Name: 0, dtype: object

In [ ]:
# Using label

data = {
    "calories": [420,380,390],
    "duration": [50,40,45]
}

df = pd.DataFrame(data,index=["day1","day2","day3"])
# print(df)

df.loc["day1"]

      calories  duration
day1       420        50
day2       380        40
day3       390        45

calories    420
duration     50
Name: day1, dtype: int64

In [ ]:
# Selecting multiple rows

df.iloc[0:2]

      calories  duration
day1       420        50
day2       380        40

#Filtering Data

In [ ]:
# Filtering means Selecting rows based on condition

data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [20, 25, 30, 22, 28]
}

df = pd.DataFrame(data)
print(df)

  Name  Age
0    A   20
1    B   25
2    C   30
3    D   22
4    E   28

In [ ]:
df[df["Age"] > 20]

  Name  Age
1    B   25
2    C   30
3    D   22
4    E   28

In [ ]:
df[(df["Age"] > 20) & (df["Age"] < 30)]

  Name  Age
1    B   25
3    D   22
4    E   28

#Practice

In [ ]:
import pandas as pd

# data = {
#     "Name": ["A", "B", "C", "D"],
#     "Age": [20, 25, 30, 22],
#     "City": ["Kochi", "Delhi", "Mumbai", "Kochi"]
# }

# df = pd.DataFrame(data)

# Tasks:
# 1. Show first 2 rows
# 2. Print column names
# 3. Select "Name" column
# 4. Select rows where Age > 22
# 5. Select people from Kochi

#Sorting Data

In [ ]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [23, 25, 22, 24, 28],
    "Marks": [85, 90, 78, 88, 92]
}

df = pd.DataFrame(data)
df

  Name  Age  Marks
0    A   23     85
1    B   25     90
2    C   22     78
3    D   24     88
4    E   28     92

In [ ]:
# Sort by Marks

df.sort_values("Marks")

  Name  Age  Marks
2    C   22     78
0    A   23     85
3    D   24     88
1    B   25     90
4    E   28     92

In [ ]:
# Descending order
df.sort_values("Marks", ascending=False)

  Name  Age  Marks
4    E   28     92
1    B   25     90
3    D   24     88
0    A   23     85
2    C   22     78

In [ ]:
# Multiple columns

df.sort_values(["Marks", "Age"])

  Name  Age  Marks
2    C   22     78
0    A   23     85
3    D   24     88
1    B   25     90
4    E   28     92

#GroupBy

In [ ]:
data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Department": ["HR", "IT", "HR", "IT", "HR"],
    "Salary": [30000, 50000, 35000, 60000, 40000]
}

df = pd.DataFrame(data)
df

  Name Department  Salary
0    A         HR   30000
1    B         IT   50000
2    C         HR   35000
3    D         IT   60000
4    E         HR   40000

In [ ]:
# Group by Department

df.groupby("Department")

In [ ]:
# Aggregation

# Average salary per department

df.groupby("Department")["Salary"].mean()

Department
HR    35000.0
IT    55000.0
Name: Salary, dtype: float64

In [ ]:
# Multiple aggregations

df.groupby("Department")["Salary"].agg(["mean", "sum", "max"])

               mean     sum    max
Department
HR          35000.0  105000  40000
IT          55000.0  110000  60000

In [ ]:
# Count employees per department

df.groupby("Department")["Name"].count()

Department
HR    3
IT    2
Name: Name, dtype: int64

#Practice

In [ ]:
# data = {
#     "Name": ["A", "B", "C", "D", "E"],
#     "Department": ["HR", "IT", "HR", "IT", "HR"],
#     "Salary": [30000, 50000, 35000, 60000, 40000]
# }

# df = pd.DataFrame(data)

# 1. Filter employees with Salary > 40000
# 2. Sort dataset by Salary (descending)
# 3. Find average salary per department
# 4. Find total salary per department
# 5. Find highest salary in each department

In [ ]:
#Answers

# Q1
df[df["Salary"] > 40000]

# Q2
df.sort_values("Salary", ascending=False)

# Q3
df.groupby("Department")["Salary"].mean()

# Q4
df.groupby("Department")["Salary"].sum()

# Q5
df.groupby("Department")["Salary"].max()

#Mini Project: Student Performance Analysis

In [ ]:
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D", "E", "F", "G", "H"],
    "Department": ["CS", "IT", "CS", "IT", "EC", "CS", "EC", "IT"],
    "Age": [20, 21, 19, 22, 20, 23, 21, 20],
    "Marks": [85, 78, 92, 70, 88, 95, 60, 82]
}

df = pd.DataFrame(data)

**Basic Exploration**
1. Show first 5 rows
2. Show last 3 rows
3. Find:
  *   number of rows & columns
  *   column names
  *   data types

**Selection & Filtering**

4. Select only "Name" and "Marks" columns
5. Show students who scored more than 80
6. Show students with:
  * Marks > 80
  * Age < 21
7. Show students from CS department

**Sorting**

8. Sort students by Marks (ascending)
9. Sort students by Marks (descending)
10. Sort by Department, then Marks

**GroupBy + Aggregation**

11. Find average marks per department
12. Find total marks per department
13. Find maximum marks per department
14. Count number of students in each department

In [ ]:
# Part 1
df.head()
df.tail(3)
df.shape
df.columns
df.info()

# Part 2
df[["Name", "Marks"]]
df[df["Marks"] > 80]
df[(df["Marks"] > 80) & (df["Age"] < 21)]
df[df["Department"] == "CS"]

# Part 3
df.sort_values("Marks")
df.sort_values("Marks", ascending=False)
df.sort_values(["Department", "Marks"])

# Part 4
df.groupby("Department")["Marks"].mean()
df.groupby("Department")["Marks"].sum()
df.groupby("Department")["Marks"].max()
df.groupby("Department")["Name"].count()