## Data processing

giving numbers to the label, so that the machine learning model can train better

nammal data thammil , oru relationship ondengi , we use label encoding or else we use one hot encoding

In [1]:
import pandas as pd

In [2]:
from sklearn.preprocessing import LabelEncoder

In [3]:
path = "/home/silvy_linux/Desktop/Internship/Datasets/breast_cancer.csv"
df = pd.read_csv(path)

In [4]:
df

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [ ]:
df['diagnosis'].value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [6]:
label_encode = LabelEncoder()

In [7]:
labels = label_encode.fit_transform(df.diagnosis)

In [8]:
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0])

In [9]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [11]:
df_new = df.drop("diagnosis",axis = 1)

In [12]:
df_new

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

## one hot encoding

In [2]:
import pandas as pd

In [3]:
path = "/home/silvy_linux/Desktop/Internship/Datasets/housing_data.csv"

df = pd.read_csv(path)

In [4]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [5]:
dummies = pd.get_dummies(df.town,dtype = int)
dummies

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [6]:
merged = pd.concat([df,dummies],axis = "columns")
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [7]:
print(merged.columns)

Index(['town', 'area', 'price', 'monroe township', 'robinsville',
       'west windsor'],
      dtype='str')

In [8]:
merged.drop(['town'],axis="columns",inplace = True)

In [9]:
print(merged)

    area   price  monroe township  robinsville  west windsor
0   2600  550000                1            0             0
1   3000  565000                1            0             0
2   3200  610000                1            0             0
3   3600  680000                1            0             0
4   4000  725000                1            0             0
5   2600  585000                0            0             1
6   2800  615000                0            0             1
7   3300  650000                0            0             1
8   3600  710000                0            0             1
9   2600  575000                0            1             0
10  2900  600000                0            1             0
11  3100  620000                0            1             0
12  3600  695000                0            1             0

## using onehot encoder

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
path = "/home/silvy_linux/Desktop/Internship/Datasets/housing_data.csv"
df = pd.read_csv(path)

In [3]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [4]:
ohe = OneHotEncoder(handle_unknown='ignore',sparse_output=False).set_output(transform='pandas')

In [6]:
ohetransform = ohe.fit_transform(df[['town']])

In [7]:
ohetransform

    town_monroe township  town_robinsville  town_west windsor
0                    1.0               0.0                0.0
1                    1.0               0.0                0.0
2                    1.0               0.0                0.0
3                    1.0               0.0                0.0
4                    1.0               0.0                0.0
5                    0.0               0.0                1.0
6                    0.0               0.0                1.0
7                    0.0               0.0                1.0
8                    0.0               0.0                1.0
9                    0.0               1.0                0.0
10                   0.0               1.0                0.0
11                   0.0               1.0                0.0
12                   0.0               1.0                0.0

In [9]:
df = pd.concat([df,ohetransform],axis='columns')

In [10]:
df

               town  area  ...  town_robinsville  town_west windsor
0   monroe township  2600  ...               0.0                0.0
1   monroe township  3000  ...               0.0                0.0
2   monroe township  3200  ...               0.0                0.0
3   monroe township  3600  ...               0.0                0.0
4   monroe township  4000  ...               0.0                0.0
5      west windsor  2600  ...               0.0                1.0
6      west windsor  2800  ...               0.0                1.0
7      west windsor  3300  ...               0.0                1.0
8      west windsor  3600  ...               0.0                1.0
9       robinsville  2600  ...               1.0                0.0
10      robinsville  2900  ...               1.0                0.0
11      robinsville  3100  ...               1.0                0.0
12      robinsville  3600  ...               1.0                0.0

[13 rows x 6 columns]

In [11]:
df.drop(['town'],axis='columns',inplace=True)

In [12]:
df

    area   price  town_monroe township  town_robinsville  town_west windsor
0   2600  550000                   1.0               0.0                0.0
1   3000  565000                   1.0               0.0                0.0
2   3200  610000                   1.0               0.0                0.0
3   3600  680000                   1.0               0.0                0.0
4   4000  725000                   1.0               0.0                0.0
5   2600  585000                   0.0               0.0                1.0
6   2800  615000                   0.0               0.0                1.0
7   3300  650000                   0.0               0.0                1.0
8   3600  710000                   0.0               0.0                1.0
9   2600  575000                   0.0               1.0                0.0
10  2900  600000                   0.0               1.0                0.0
11  3100  620000                   0.0               1.0                0.0
12  3600  695000                   0.0               1.0                0.0

## performing encoding techniques using this

practise of both - label and one hot encoding

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
d = {'sales': [100000,222000,1000000,522000,111111,222222,1111111,20000,75000,90000,1000000,10000],
'city': ['Tampa','Tampa','Orlando','Jacksonville','Miami','Jacksonville','Miami','Miami','Orlando','Orlando','Orlando','Orlando'],
'size': ['Small', 'Medium','Large','Large','Small','Medium','Large','Small','Medium','Medium','Medium','Small',]}

df = pd.DataFrame(d)

In [3]:
print(df)

      sales          city    size
0    100000         Tampa   Small
1    222000         Tampa  Medium
2   1000000       Orlando   Large
3    522000  Jacksonville   Large
4    111111         Miami   Small
5    222222  Jacksonville  Medium
6   1111111         Miami   Large
7     20000         Miami   Small
8     75000       Orlando  Medium
9     90000       Orlando  Medium
10  1000000       Orlando  Medium
11    10000       Orlando   Small

In [4]:
#performing one hot encoding on city
ohe = OneHotEncoder(handle_unknown='ignore',sparse_output=False).set_output(transform='pandas')

In [5]:
ohetransform = ohe.fit_transform(df[['city']])

In [6]:
ohetransform

    city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                 0.0         0.0           0.0         1.0
1                 0.0         0.0           0.0         1.0
2                 0.0         0.0           1.0         0.0
3                 1.0         0.0           0.0         0.0
4                 0.0         1.0           0.0         0.0
5                 1.0         0.0           0.0         0.0
6                 0.0         1.0           0.0         0.0
7                 0.0         1.0           0.0         0.0
8                 0.0         0.0           1.0         0.0
9                 0.0         0.0           1.0         0.0
10                0.0         0.0           1.0         0.0
11                0.0         0.0           1.0         0.0

In [7]:
df = pd.concat([df,ohetransform],axis='columns')

In [8]:
df.drop(['city'],axis='columns',inplace=True)

In [9]:
df

      sales    size  city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0    100000   Small                0.0         0.0           0.0         1.0
1    222000  Medium                0.0         0.0           0.0         1.0
2   1000000   Large                0.0         0.0           1.0         0.0
3    522000   Large                1.0         0.0           0.0         0.0
4    111111   Small                0.0         1.0           0.0         0.0
5    222222  Medium                1.0         0.0           0.0         0.0
6   1111111   Large                0.0         1.0           0.0         0.0
7     20000   Small                0.0         1.0           0.0         0.0
8     75000  Medium                0.0         0.0           1.0         0.0
9     90000  Medium                0.0         0.0           1.0         0.0
10  1000000  Medium                0.0         0.0           1.0         0.0
11    10000   Small                0.0         0.0           1.0         0.0

In [10]:
#now performing label encoding
df["size"].value_counts()

size
Medium    5
Small     4
Large     3
Name: count, dtype: int64

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
label_encode = LabelEncoder()

In [18]:
labels = label_encode.fit_transform(df['size'])

In [19]:
labels

array([2, 1, 0, 0, 2, 1, 0, 2, 1, 1, 1, 2])

In [20]:
df.head()

     sales    size  city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0   100000   Small                0.0         0.0           0.0         1.0
1   222000  Medium                0.0         0.0           0.0         1.0
2  1000000   Large                0.0         0.0           1.0         0.0
3   522000   Large                1.0         0.0           0.0         0.0
4   111111   Small                0.0         1.0           0.0         0.0

In [21]:
df_new = df.drop("size",axis = 1)

In [22]:
df_new

      sales  city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0    100000                0.0         0.0           0.0         1.0
1    222000                0.0         0.0           0.0         1.0
2   1000000                0.0         0.0           1.0         0.0
3    522000                1.0         0.0           0.0         0.0
4    111111                0.0         1.0           0.0         0.0
5    222222                1.0         0.0           0.0         0.0
6   1111111                0.0         1.0           0.0         0.0
7     20000                0.0         1.0           0.0         0.0
8     75000                0.0         0.0           1.0         0.0
9     90000                0.0         0.0           1.0         0.0
10  1000000                0.0         0.0           1.0         0.0
11    10000                0.0         0.0           1.0         0.0